const styleShorthand = {
  fz: ['font-size'],
  fw: ['font-weight'],
  lh: ['line-height'],
  ls: ['letter-spacing'],
  pt: ['padding-top'],
  pb: ['padding-bottom'],
  ps: ['padding-left'],
  pl: ['padding-left'],
  pe: ['padding-left'],
  pr: ['padding-right'],
  py: ['padding-top', 'padding-bottom'],
  px: ['padding-left', 'padding-right'],
  mt: ['margin-top'],
  mb: ['margin-bottom'],
  ms: ['margin-left'],
  ml: ['margin-left'],
  me: ['margin-left'],
  mr: ['margin-right'],
  my: ['margin-top', 'margin-bottom'],
  mx: ['margin-left', 'margin-right'],
}